"""oauth state table; calendar_connections.refresh_token becomes nullable

Revision ID: 0004_oauth_state
Revises: 0003_align_phase1_checks
Create Date: 2026-09-20

Autogenerated, then adjusted. Two changes, both marked [ADJUSTED].

A LIVE DEMONSTRATION OF THE 0003 FINDING: autogenerate detected the new
table, its two indexes and the nullability change -- and completely missed
the new CHECK constraint `ck_calendar_connections_active_requires_refresh_token`,
because autogenerate does not compare CHECK constraints. It had to be added
by hand below. This is the second time in four migrations that the gap has
bitten, which is why the pg_constraint-vs-models CI job is worth doing.

WHY refresh_token BECOMES NULLABLE
----------------------------------
Disconnecting a calendar must destroy the stored credential. It cannot do
that by deleting the row: calendar_connections CASCADEs to
external_busy_blocks, and schedule_conflicts references those with RESTRICT
(0003), so a hard delete raises a ForeignKeyViolation for exactly the
doctors who have had a booking collide with their personal calendar -- the
ones whose audit trail matters most. So "disconnect" nulls the secrets and
sets state='disabled', keeping the row as history.

The new CHECK keeps that from becoming a footgun: an ACTIVE connection with
no refresh token is a connection that stops working within the hour and
cannot recover, so the database now refuses to represent it.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0004_oauth_state"
down_revision: Union[str, None] = "0003_align_phase1_checks"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# [ADJUSTED #1] Autogenerate emitted `app.db.types.EncryptedString()` with no
# import, which would NameError on first run. Same reasoning as migration
# 0002: migrations must not import application code, because a rename years
# from now would break the ability to rebuild the database from scratch.
# EncryptedString's impl is Text, so the DDL is identical.
_ENCRYPTED = sa.Text

_ACTIVE_NEEDS_TOKEN = "ck_calendar_connections_active_requires_refresh_token"


def upgrade() -> None:
    op.create_table(
        "oauth_states",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("state_token", sa.String(length=128), nullable=False),
        sa.Column("doctor_id", sa.UUID(), nullable=False),
        # PKCE verifier -- a bearer secret, encrypted at rest.
        sa.Column("code_verifier", _ENCRYPTED(), nullable=False),
        sa.Column("redirect_uri", sa.String(length=2048), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["doctor_id"], ["doctors.id"],
            name=op.f("fk_oauth_states_doctor_id_doctors"), ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_states")),
    )
    # Drives the (not yet written) expiry cleanup job.
    op.create_index("ix_oauth_states_expires_at", "oauth_states", ["expires_at"], unique=False)
    # The CSRF token must be unique; the callback looks the row up by it.
    op.create_index("uq_oauth_states_state_token", "oauth_states", ["state_token"], unique=True)

    op.alter_column(
        "calendar_connections", "refresh_token", existing_type=sa.TEXT(), nullable=True
    )

    # [ADJUSTED #2] Added by hand -- autogenerate does not diff CHECK
    # constraints and silently omitted this.
    #
    # NOT VALID is deliberate: it applies the constraint to all future
    # writes without scanning the existing table, so this migration takes an
    # ACCESS EXCLUSIVE lock only for a catalog update rather than for a full
    # scan. VALIDATE CONSTRAINT then checks existing rows under a far weaker
    # SHARE UPDATE EXCLUSIVE lock that does not block reads or writes.
    #
    # On a table this small it makes no measurable difference; it is written
    # this way because it is the pattern you want burned in before the table
    # is large, when getting it wrong means locking out every booking.
    op.execute(
        f"ALTER TABLE calendar_connections ADD CONSTRAINT {_ACTIVE_NEEDS_TOKEN} "
        "CHECK (state <> 'active' OR refresh_token IS NOT NULL) NOT VALID"
    )
    op.execute(f"ALTER TABLE calendar_connections VALIDATE CONSTRAINT {_ACTIVE_NEEDS_TOKEN}")


def downgrade() -> None:
    op.execute(f"ALTER TABLE calendar_connections DROP CONSTRAINT {_ACTIVE_NEEDS_TOKEN}")

    # NOTE: this will fail if any row has a NULL refresh_token -- i.e. if any
    # calendar has been disconnected since the upgrade. That is correct
    # behaviour, not a bug: silently deleting or fabricating credentials to
    # satisfy a NOT NULL would be far worse than refusing. Resolve by
    # deleting the disconnected rows deliberately, then retry.
    op.alter_column(
        "calendar_connections", "refresh_token", existing_type=sa.TEXT(), nullable=False
    )

    op.drop_index("uq_oauth_states_state_token", table_name="oauth_states")
    op.drop_index("ix_oauth_states_expires_at", table_name="oauth_states")
    op.drop_table("oauth_states")
