"""staff accounts (auth), appointment reschedule tracking

Revision ID: 0005_auth_reschedule
Revises: 0004_oauth_state
Create Date: 2026-09-21

Autogenerated, then adjusted. One change, marked [ADJUSTED].

ANOTHER LIVE DEMONSTRATION OF THE 0003 FINDING: adding
`NotificationKind.RESCHEDULE_CONFIRMATION` to the model widens the CHECK
constraint `ck_notifications_notification_kind` (it is generated FROM the
enum, via create_constraint=True). Autogenerate detected the new table, the
new column and its FK -- and said nothing at all about the CHECK, because
autogenerate does not compare CHECK constraints. Caught here only because
every migration in this project is diffed against `pg_constraint` by hand
before being trusted; see scripts/check_schema_drift.py for the automated
version of that same check, and the third time in five migrations this
exact gap has produced silent drift.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0005_auth_reschedule"
down_revision: Union[str, None] = "0004_oauth_state"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_KIND_CHECK = "ck_notifications_notification_kind"
_OLD_KINDS = "'booking_confirmation', 'reminder_24h', 'cancellation_confirmation'"
_NEW_KINDS = "'booking_confirmation', 'reminder_24h', 'cancellation_confirmation', 'reschedule_confirmation'"


def upgrade() -> None:
    # ------------------------------------------------------------------ #
    # staff_accounts -- see models/staff_account.py for the CHECK's intent
    # ------------------------------------------------------------------ #
    op.create_table(
        "staff_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("doctor", "front_desk", name="staff_role", native_enum=False, create_constraint=True, length=16),
            nullable=False,
        ),
        sa.Column("doctor_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(role = 'doctor' AND doctor_id IS NOT NULL) OR (role = 'front_desk' AND doctor_id IS NULL)",
            name=op.f("ck_staff_accounts_doctor_role_requires_doctor_id"),
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"], ["doctors.id"],
            name=op.f("fk_staff_accounts_doctor_id_doctors"), ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff_accounts")),
        sa.UniqueConstraint("email", name=op.f("uq_staff_accounts_email")),
    )

    # ------------------------------------------------------------------ #
    # appointments.rescheduled_from_id -- self-referential audit link
    # ------------------------------------------------------------------ #
    op.add_column("appointments", sa.Column("rescheduled_from_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_appointments_rescheduled_from_id_appointments"),
        "appointments", "appointments", ["rescheduled_from_id"], ["id"], ondelete="RESTRICT",
    )

    # ------------------------------------------------------------------ #
    # [ADJUSTED] Widen the notification_kind CHECK for RESCHEDULE_CONFIRMATION.
    #
    # Widening (adding an allowed value) can never invalidate an existing
    # row -- every row already satisfies the narrower set, so it trivially
    # satisfies the wider one. NOT VALID + VALIDATE is used anyway, as a
    # matter of habit worth keeping even when it is provably unnecessary:
    # it is the only form that is ALWAYS safe regardless of which direction
    # a future edit to this pattern goes, and it costs nothing on a small
    # table today. See migration 0004 for the case where it actually
    # matters (locking).
    # ------------------------------------------------------------------ #
    op.execute(f"ALTER TABLE notifications DROP CONSTRAINT {_KIND_CHECK}")
    op.execute(
        f"ALTER TABLE notifications ADD CONSTRAINT {_KIND_CHECK} "
        f"CHECK (kind IN ({_NEW_KINDS})) NOT VALID"
    )
    op.execute(f"ALTER TABLE notifications VALIDATE CONSTRAINT {_KIND_CHECK}")


def downgrade() -> None:
    # NOTE: this will fail if any row has kind='reschedule_confirmation' --
    # i.e. if any reschedule notification was ever sent. That is correct:
    # silently deleting or reclassifying those rows to satisfy a narrower
    # constraint would corrupt the notification audit trail. Resolve by
    # deleting or migrating those rows deliberately, then retry.
    op.execute(f"ALTER TABLE notifications DROP CONSTRAINT {_KIND_CHECK}")
    op.execute(
        f"ALTER TABLE notifications ADD CONSTRAINT {_KIND_CHECK} "
        f"CHECK (kind IN ({_OLD_KINDS})) NOT VALID"
    )
    op.execute(f"ALTER TABLE notifications VALIDATE CONSTRAINT {_KIND_CHECK}")

    op.drop_constraint(
        op.f("fk_appointments_rescheduled_from_id_appointments"), "appointments", type_="foreignkey"
    )
    op.drop_column("appointments", "rescheduled_from_id")
    op.drop_table("staff_accounts")
