"""chatbot conversations, booking proposals, patient date of birth

Revision ID: 0006_conversations
Revises: 0005_auth_reschedule
Create Date: 2026-09-21

Autogenerated and, unusually for this project, NOT adjusted -- the output
was correct as generated. Recorded explicitly rather than left unsaid,
because the last three migrations all needed a hand-written CHECK fix and
it would be easy to assume this one silently did too.

WHY THIS ONE WAS CLEAN, precisely: autogenerate's CHECK blind spot applies
to MODIFYING constraints on an existing table (widening an enum's allowed
values, which is what bit 0003/0004/0005). Constraints on a BRAND NEW
table come through `create_table` inline and are emitted correctly. This
migration adds two new tables and one nullable column, and widens nothing
-- so there was nothing in the blind spot to miss. The drift check
(scripts/check_schema_drift.py) was still run against it rather than
trusting that reasoning.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0006_conversations"
down_revision: Union[str, None] = "0005_auth_reschedule"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ------------------------------------------------------------------ #
    # conversations -- see models/conversation.py. patient_id here is the
    # single source of truth for who a chatbot conversation may act for.
    # ------------------------------------------------------------------ #
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum("sms", "voice", "web", name="conversation_channel", native_enum=False, create_constraint=True, length=16),
            nullable=False,
        ),
        sa.Column("external_ref", sa.String(length=128), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=True),
        sa.Column("identity_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("identity_attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "escalated", "completed", "expired", name="conversation_status", native_enum=False, create_constraint=True, length=16),
            server_default="active",
            nullable=False,
        ),
        sa.Column("escalation_reason", sa.Text(), nullable=True),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        # "verified" and "bound to a patient" must be the same state --
        # neither half is meaningful alone.
        sa.CheckConstraint(
            "(patient_id IS NULL AND identity_verified_at IS NULL) OR "
            "(patient_id IS NOT NULL AND identity_verified_at IS NOT NULL)",
            name=op.f("ck_conversations_verified_iff_patient_bound"),
        ),
        sa.CheckConstraint("identity_attempts >= 0", name=op.f("ck_conversations_attempts_non_negative")),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["patients.id"],
            name=op.f("fk_conversations_patient_id_patients"), ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    # Partial: the inbound-message lookup only ever wants live conversations.
    op.create_index(
        "ix_conversations_active_external_ref",
        "conversations",
        ["channel", "external_ref"],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )

    # ------------------------------------------------------------------ #
    # booking_proposals -- the two-phase commit that keeps the language
    # model out of the trust path. See models/booking_proposal.py.
    # ------------------------------------------------------------------ #
    op.create_table(
        "booking_proposals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("book", "cancel", name="proposal_kind", native_enum=False, create_constraint=True, length=16),
            nullable=False,
        ),
        sa.Column("time_slot_id", sa.UUID(), nullable=True),
        sa.Column("appointment_id", sa.UUID(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        # A proposal points at exactly the one thing its kind implies.
        sa.CheckConstraint(
            "(kind = 'book' AND time_slot_id IS NOT NULL AND appointment_id IS NULL) OR "
            "(kind = 'cancel' AND appointment_id IS NOT NULL AND time_slot_id IS NULL)",
            name=op.f("ck_booking_proposals_kind_matches_target"),
        ),
        sa.ForeignKeyConstraint(
            ["appointment_id"], ["appointments.id"],
            name=op.f("fk_booking_proposals_appointment_id_appointments"), ondelete="RESTRICT",
        ),
        # CASCADE from the conversation: a proposal is an offer made inside
        # one conversation and is meaningless outside it. Unlike the audit
        # trails elsewhere in this schema, there is nothing here worth
        # keeping once the conversation is gone -- the APPOINTMENT it
        # produced is the durable record, and that is untouched.
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"],
            name=op.f("fk_booking_proposals_conversation_id_conversations"), ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["patients.id"],
            name=op.f("fk_booking_proposals_patient_id_patients"), ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["time_slot_id"], ["time_slots.id"],
            name=op.f("fk_booking_proposals_time_slot_id_time_slots"), ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_booking_proposals")),
    )
    op.create_index(
        "ix_booking_proposals_conversation_id", "booking_proposals", ["conversation_id"], unique=False
    )

    # ------------------------------------------------------------------ #
    # patients.date_of_birth -- the chatbot's second factor.
    #
    # NULLABLE on purpose: every patient created before this migration has
    # none, and real clinic records always contain some without one. A
    # patient with no DOB cannot be verified by chatbot and is escalated to
    # a human. See models/patient.py.
    # ------------------------------------------------------------------ #
    op.add_column("patients", sa.Column("date_of_birth", sa.Date(), nullable=True))


def downgrade() -> None:
    op.drop_column("patients", "date_of_birth")
    op.drop_index("ix_booking_proposals_conversation_id", table_name="booking_proposals")
    op.drop_table("booking_proposals")
    op.drop_index("ix_conversations_active_external_ref", table_name="conversations")
    op.drop_table("conversations")
