"""conversation message transcript

Revision ID: 0007_conversation_messages
Revises: 0006_conversations
Create Date: 2026-09-22

Autogenerated, then adjusted. One change, marked [ADJUSTED] -- the same
`app.db.types.EncryptedString` reference that had to be removed from
migrations 0002 and 0004, for the same reason. Third occurrence: any
migration touching an encrypted column will generate it, so expect it
rather than rediscovering it.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0007_conversation_messages"
down_revision: Union[str, None] = "0006_conversations"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# [ADJUSTED] Autogenerate emitted `app.db.types.EncryptedString()` with no
# import, which NameErrors on first run. The fix is not to add the import:
# a migration must still run years from now, and importing application
# code means renaming that class breaks the ability to rebuild the
# database from scratch. Encryption is applied in the application layer
# and leaves no trace in the DDL, so Text is byte-identical here.
_ENCRYPTED = sa.Text


def upgrade() -> None:
    op.create_table(
        "conversation_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("user", "assistant", "tool", name="message_role", native_enum=False, create_constraint=True, length=16),
            nullable=False,
        ),
        # Encrypted at rest by the application -- the most sensitive
        # column in this database. See models/conversation_message.py.
        sa.Column("content", _ENCRYPTED(), nullable=True),
        sa.Column("tool_payload", _ENCRYPTED(), nullable=True),
        sa.Column("tool_name", sa.String(length=64), nullable=True),
        sa.Column("provider_message_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("sequence >= 0", name=op.f("ck_conversation_messages_sequence_non_negative")),
        # CASCADE: a transcript belongs to its conversation and is
        # meaningless without it. Note this differs from the audit trails
        # elsewhere in the schema -- the durable record of what was AGREED
        # is the appointment row, which is untouched by this.
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"],
            name=op.f("fk_conversation_messages_conversation_id_conversations"), ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversation_messages")),
    )
    # Deterministic replay order, and a gap is visible rather than silent.
    op.create_index(
        "uq_conversation_messages_conversation_id_sequence",
        "conversation_messages", ["conversation_id", "sequence"], unique=True,
    )
    # THE WEBHOOK IDEMPOTENCY GUARANTEE. Twilio retries deliveries; a
    # retried webhook must not be processed as a second patient message.
    # Partial, since only inbound rows carry a provider id.
    op.create_index(
        "uq_conversation_messages_provider_message_id",
        "conversation_messages", ["provider_message_id"], unique=True,
        postgresql_where=sa.text("provider_message_id IS NOT NULL"),
    )


def downgrade() -> None:
    op.drop_index("uq_conversation_messages_provider_message_id", table_name="conversation_messages")
    op.drop_index("uq_conversation_messages_conversation_id_sequence", table_name="conversation_messages")
    op.drop_table("conversation_messages")
