"""sms reply outbox

Revision ID: 0008_sms_reply_jobs
Revises: 0007_conversation_messages
Create Date: 2026-09-22

Autogenerated, then adjusted. One change, marked [ADJUSTED] -- the
`app.db.types.EncryptedString` reference again, for the FOURTH time
(0002, 0004, 0007, 0008). It is now entirely predictable: any migration
touching an encrypted column generates it. Not a surprise, just a step.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0008_sms_reply_jobs"
down_revision: Union[str, None] = "0007_conversation_messages"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# [ADJUSTED] See the docstring. A migration must not import application
# code -- renaming that class would break rebuilding the database from
# scratch. Encryption happens in the app layer and leaves no trace in
# the DDL, so Text is byte-identical.
_ENCRYPTED = sa.Text


def upgrade() -> None:
    op.create_table(
        "sms_reply_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        # The ingestion idempotency key -- a Twilio retry is a duplicate
        # delivery of one message, not a second message.
        sa.Column("provider_message_id", sa.String(length=255), nullable=False),
        # Patient text, encrypted at rest (see models/sms_reply_job.py).
        sa.Column("inbound_body", _ENCRYPTED(), nullable=True),
        sa.Column("reply_to", sa.String(length=32), nullable=False),
        # NULL until the conversation loop has run. The marker that makes
        # a retry after a crash safe: a job with a reply already decided
        # skips straight to sending rather than re-invoking the model and
        # possibly acting twice.
        sa.Column("reply_body", _ENCRYPTED(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "claimed", "sent", "failed", "abandoned", "skipped", "unresolved",
                name="notification_status", native_enum=False, create_constraint=True, length=32,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="3", nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_send_id", sa.String(length=255), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_sms_reply_jobs_attempts_non_negative")),
        sa.CheckConstraint(
            "status <> 'sent' OR sent_at IS NOT NULL", name=op.f("ck_sms_reply_jobs_sent_requires_sent_at")
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"],
            name=op.f("fk_sms_reply_jobs_conversation_id_conversations"), ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_reply_jobs")),
    )
    op.create_index(
        "uq_sms_reply_jobs_provider_message_id", "sms_reply_jobs", ["provider_message_id"], unique=True
    )
    # The worker's claim query. Partial -- sent rows accumulate forever
    # and are never work.
    op.create_index(
        "ix_sms_reply_jobs_claimable",
        "sms_reply_jobs",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('pending','failed')"),
    )


def downgrade() -> None:
    op.drop_index("ix_sms_reply_jobs_claimable", table_name="sms_reply_jobs")
    op.drop_index("uq_sms_reply_jobs_provider_message_id", table_name="sms_reply_jobs")
    op.drop_table("sms_reply_jobs")
