"""notification target widening for escalation paging (Phase 3.5)

Revision ID: 0009_escalation_notify
Revises: 0008_sms_reply_jobs
Create Date: 2026-09-22

Autogenerated, then adjusted. THREE changes, marked [ADJUSTED] -- and
the third is a NEW category of gap for this project, not a repeat of
the familiar one.

Autogenerate correctly caught: the new `conversation_id` column, its FK,
its own (already-partial) index, and `appointment_id` becoming nullable.

Autogenerate MISSED, as expected by now: widening the `notification_kind`
CHECK to allow 'escalation', and the brand-new `kind_matches_target`
CHECK. Both are CHECK-constraint changes -- the same permanent blind
spot as migrations 0003/0004/0005/0007/0008.

Autogenerate ALSO MISSED something not seen before on this project:
`ix_notifications_appointment_id` changing from a full index to a
PARTIAL one (`WHERE appointment_id IS NOT NULL`). This is not a CHECK
constraint at all -- it is an index PREDICATE change on an index
autogenerate otherwise knows exists. The pattern generalizes further
than "CHECK constraints" alone: autogenerate compares index EXISTENCE
and COLUMNS, not arbitrary WHERE-clause text, on either object type.
Recorded here, and worth folding into the project's schema-drift memory
note rather than treated as a one-off -- scripts/check_schema_drift.py
already catches this class (it diffs full index DEFINITIONS, not just
names), which is exactly why that script exists.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0009_escalation_notify"
down_revision: Union[str, None] = "0008_sms_reply_jobs"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_KIND_CHECK = "ck_notifications_notification_kind"
_OLD_KINDS = "'booking_confirmation', 'reminder_24h', 'cancellation_confirmation', 'reschedule_confirmation'"
_NEW_KINDS = _OLD_KINDS + ", 'escalation'"
_TARGET_CHECK = "ck_notifications_kind_matches_target"


def upgrade() -> None:
    # ------------------------------------------------------------------ #
    # New target column for conversation-level (not appointment-level)
    # notifications -- currently only 'escalation'. See models/notification.py.
    # ------------------------------------------------------------------ #
    op.add_column("notifications", sa.Column("conversation_id", sa.UUID(), nullable=True))
    op.alter_column("notifications", "appointment_id", existing_type=sa.UUID(), nullable=True)
    op.create_foreign_key(
        op.f("fk_notifications_conversation_id_conversations"),
        "notifications", "conversations", ["conversation_id"], ["id"], ondelete="RESTRICT",
    )
    op.create_index(
        "ix_notifications_conversation_id", "notifications", ["conversation_id"],
        unique=False, postgresql_where=sa.text("conversation_id IS NOT NULL"),
    )

    # ------------------------------------------------------------------ #
    # [ADJUSTED #1] ix_notifications_appointment_id: full -> partial.
    #
    # Plain DROP + CREATE, not CONCURRENTLY. Correct and sufficient for
    # this table's current size; at real production scale this pair
    # should become two separate migrations run outside a transaction
    # (CREATE INDEX CONCURRENTLY, verify, DROP INDEX CONCURRENTLY) to
    # avoid holding a lock across an index build on a live table. Not
    # done that way here because introducing that ceremony before it is
    # needed obscures the actual change; flagged so it is not forgotten
    # if this table ever gets large before this migration is long past.
    # ------------------------------------------------------------------ #
    op.drop_index("ix_notifications_appointment_id", table_name="notifications")
    op.create_index(
        "ix_notifications_appointment_id", "notifications", ["appointment_id"],
        unique=False, postgresql_where=sa.text("appointment_id IS NOT NULL"),
    )

    # ------------------------------------------------------------------ #
    # [ADJUSTED #2] Widen notification_kind for 'escalation'.
    # NOT VALID + VALIDATE: widening can never invalidate an existing row
    # (every row already satisfies the narrower set), but this keeps the
    # pattern uniform with every other CHECK change in this project --
    # see migration 0005 for the case where that uniformity actually
    # matters (locking).
    # ------------------------------------------------------------------ #
    op.execute(f"ALTER TABLE notifications DROP CONSTRAINT {_KIND_CHECK}")
    op.execute(
        f"ALTER TABLE notifications ADD CONSTRAINT {_KIND_CHECK} "
        f"CHECK (kind IN ({_NEW_KINDS})) NOT VALID"
    )
    op.execute(f"ALTER TABLE notifications VALIDATE CONSTRAINT {_KIND_CHECK}")

    # ------------------------------------------------------------------ #
    # [ADJUSTED #3] The new kind_matches_target CHECK -- autogenerate
    # said nothing about this at all. Safe as NOT VALID + VALIDATE
    # against existing data: every row created before this migration has
    # kind <> 'escalation' and appointment_id IS NOT NULL (conversation_id
    # is a column this same migration just added, so it is NULL on every
    # existing row) -- exactly what the first branch of the CHECK
    # requires, so VALIDATE cannot fail against real data by construction.
    # ------------------------------------------------------------------ #
    op.execute(
        f"ALTER TABLE notifications ADD CONSTRAINT {_TARGET_CHECK} "
        "CHECK ((kind <> 'escalation' AND appointment_id IS NOT NULL AND conversation_id IS NULL) OR "
        "(kind = 'escalation' AND appointment_id IS NULL AND conversation_id IS NOT NULL)) NOT VALID"
    )
    op.execute(f"ALTER TABLE notifications VALIDATE CONSTRAINT {_TARGET_CHECK}")


def downgrade() -> None:
    op.execute(f"ALTER TABLE notifications DROP CONSTRAINT {_TARGET_CHECK}")

    # NOTE: this will fail if any row has kind='escalation' -- i.e. if any
    # escalation notification was ever sent. Correct: silently deleting
    # or reclassifying those rows to satisfy a narrower schema would
    # corrupt the notification audit trail. Resolve deliberately, then
    # retry.
    op.execute(f"ALTER TABLE notifications DROP CONSTRAINT {_KIND_CHECK}")
    op.execute(
        f"ALTER TABLE notifications ADD CONSTRAINT {_KIND_CHECK} "
        f"CHECK (kind IN ({_OLD_KINDS})) NOT VALID"
    )
    op.execute(f"ALTER TABLE notifications VALIDATE CONSTRAINT {_KIND_CHECK}")

    op.drop_index("ix_notifications_appointment_id", table_name="notifications")
    op.create_index("ix_notifications_appointment_id", "notifications", ["appointment_id"], unique=False)

    op.drop_index("ix_notifications_conversation_id", table_name="notifications")
    op.drop_constraint(
        op.f("fk_notifications_conversation_id_conversations"), "notifications", type_="foreignkey"
    )
    # Also fails loudly if any row actually used conversation_id -- same
    # reasoning as above; this NOT NULL restore is a real precondition,
    # not a formality.
    op.alter_column("notifications", "appointment_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("notifications", "conversation_id")
