"""staff reopen audit metadata on conversations (Phase 3.5)

Revision ID: 0010_conversation_reopen
Revises: 0009_escalation_notify
Create Date: 2026-09-22

Autogenerated, then adjusted. Autogenerate correctly caught the three new
nullable columns (`reopened_at`, `reopened_by_staff_id`, `reopen_reason`)
and the new FK to staff_accounts.

Autogenerate MISSED, exactly as expected by now (0003/0004/0005/0007/
0008/0009): the new `reopened_iff_staff_recorded` CHECK constraint. Not
recorded anywhere in the generated diff at all -- consistent with every
prior finding that autogenerate's constraint comparison does not see
CHECK constraints, full stop, regardless of whether the change is a
widening of an existing CHECK (0009) or, as here, a brand new one.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0010_conversation_reopen"
down_revision: Union[str, None] = "0009_escalation_notify"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_PAIR_CHECK = "ck_conversations_reopened_iff_staff_recorded"


def upgrade() -> None:
    op.add_column("conversations", sa.Column("reopened_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("conversations", sa.Column("reopened_by_staff_id", sa.UUID(), nullable=True))
    op.add_column("conversations", sa.Column("reopen_reason", sa.Text(), nullable=True))
    op.create_foreign_key(
        op.f("fk_conversations_reopened_by_staff_id_staff_accounts"),
        "conversations", "staff_accounts", ["reopened_by_staff_id"], ["id"], ondelete="RESTRICT",
    )

    # NOT VALID + VALIDATE: every existing row has both columns NULL (they
    # did not exist a moment ago), which satisfies the first branch of the
    # pair -- VALIDATE cannot fail against real data by construction, same
    # reasoning as 0009's kind_matches_target.
    op.execute(
        f"ALTER TABLE conversations ADD CONSTRAINT {_PAIR_CHECK} "
        "CHECK ((reopened_at IS NULL AND reopened_by_staff_id IS NULL) OR "
        "(reopened_at IS NOT NULL AND reopened_by_staff_id IS NOT NULL)) NOT VALID"
    )
    op.execute(f"ALTER TABLE conversations VALIDATE CONSTRAINT {_PAIR_CHECK}")


def downgrade() -> None:
    op.execute(f"ALTER TABLE conversations DROP CONSTRAINT {_PAIR_CHECK}")
    op.drop_constraint(
        op.f("fk_conversations_reopened_by_staff_id_staff_accounts"), "conversations", type_="foreignkey"
    )
    op.drop_column("conversations", "reopen_reason")
    op.drop_column("conversations", "reopened_by_staff_id")
    op.drop_column("conversations", "reopened_at")
