"""voice DOB read-back-confirm candidate (Phase 4)

Revision ID: 0011_voice_dob_pending
Revises: 0010_conversation_reopen
Create Date: 2026-09-22

Autogenerated, unadjusted -- a single nullable column with no CHECK
constraint pairing (unlike 0009/0010, `pending_dob_candidate` is not an
"iff" pair with anything else on this table, so there is nothing here
for autogenerate's known CHECK-constraint blind spot to miss). Confirmed
by `alembic check` and scripts/check_schema_drift.py below regardless,
same verification bar as every other migration in this project.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0011_voice_dob_pending"
down_revision: Union[str, None] = "0010_conversation_reopen"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("conversations", sa.Column("pending_dob_candidate", sa.Date(), nullable=True))


def downgrade() -> None:
    op.drop_column("conversations", "pending_dob_candidate")
