"""voice turn outbox, poll/redirect hold pattern (Phase 4)

Revision ID: 0012_voice_turn_jobs
Revises: 0011_voice_dob_pending
Create Date: 2026-09-22

Autogenerated, then adjusted. ONE change, marked [ADJUSTED] -- the
`app.db.types.EncryptedString` reference, for the FIFTH time now (0002,
0004, 0007, 0008, and this one). Both CHECK constraints on this table
WERE caught correctly this time, unlike every prior CHECK-constraint
finding in this project -- because this is a brand new table (CREATE
TABLE captures its constraints as part of the same statement), not an
ALTER on an existing one. Autogenerate's CHECK-constraint blind spot is
specifically about diffing constraints on tables that already exist;
recorded here so this migration is not mistaken for a counterexample to
every prior finding on that.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0012_voice_turn_jobs"
down_revision: Union[str, None] = "0011_voice_dob_pending"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# [ADJUSTED] See the docstring. A migration must not import application
# code -- renaming that class would break rebuilding the database from
# scratch. Encryption happens in the app layer and leaves no trace in
# the DDL, so Text is byte-identical.
_ENCRYPTED = sa.Text


def upgrade() -> None:
    op.create_table(
        "voice_turn_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        # Audit only, NOT a dedupe key -- see models/voice_turn_job.py.
        sa.Column("call_sid", sa.String(length=64), nullable=False),
        # Caller-authored text, encrypted at rest (same reasoning as
        # conversation_messages/sms_reply_jobs).
        sa.Column("inbound_text", _ENCRYPTED(), nullable=False),
        # NULL until the loop has run -- the marker that makes a retry
        # or a reap after a crash safe.
        sa.Column("reply_body", _ENCRYPTED(), nullable=True),
        sa.Column("conversation_ended", sa.Boolean(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "claimed", "sent", "failed", "abandoned", "skipped", "unresolved",
                name="notification_status", native_enum=False, create_constraint=True, length=32,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        # 1, not SmsReplyJob's 3 -- see the module docstring on why a
        # live-holding caller gets no background retry-over-minutes.
        sa.Column("max_attempts", sa.Integer(), server_default="1", nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_voice_turn_jobs_attempts_non_negative")),
        sa.CheckConstraint(
            "status <> 'sent' OR reply_body IS NOT NULL",
            name=op.f("ck_voice_turn_jobs_sent_requires_reply_body"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"],
            name=op.f("fk_voice_turn_jobs_conversation_id_conversations"), ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_voice_turn_jobs")),
    )
    # The worker's claim query. Partial on 'pending' only (not
    # 'pending','failed' like sms_reply_jobs) -- this table never uses
    # 'failed', see the module docstring.
    op.create_index(
        "ix_voice_turn_jobs_claimable",
        "voice_turn_jobs",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )


def downgrade() -> None:
    op.drop_index("ix_voice_turn_jobs_claimable", table_name="voice_turn_jobs")
    op.drop_table("voice_turn_jobs")
